### PR TITLE
GSP195-Updates for Python3 in 02_ingest/monthlyupdate folder

### PR DESCRIPTION
**Pull request by kalyanipande-tudip**
- Updated the python version in app.yaml file.
- Removed the flexible environment in the app.yaml as it is incompatible with python 3.
- Updated the script handlers to auto parameter in app.yaml file.
- Updated the flask version as needed for the python 3  in requirement.txt file.

### CODE REVIEW

**Comment by kalyanipande-tudip** [comment]
Hi @mylenebiddle 
Please verify the changes.

**Comment by mylenebiddle** [comment]
@kalyanipande-tudip can you resolve the conflicts? I'm getting permission denied when trying to push your fork.

**Comment by kalyanipande-tudip** [comment]
Hi @mylenebiddle,

According to lab manual, we have lab dependency on data-science-on-gcp/02_ingest/monthlyupdate/app.yaml file to deploy app but as per the PR: https://github.com/GoogleCloudPlatform/data-science-on-gcp/pull/74 (created by Lak) the app.yaml file has been removed due to which current lab is not working.

According to README.md file the dependency has been moved from app engine to cloud function so lab instructions needs to be updated according to the cloud function.

Please let us know if there is anything for us.

-Thanks!

**Comment by lakshmanok** [comment]
This functionality has been updated to use Cloud Run.  Joe Mansfield is updating the Qwiklabs to the new TensorFlow 2.0 version of the book.

**Comment by seanlubbers1** [comment]
@joemansfield any updates on this one?

**Comment by joemansfield** [comment]
Sean - we are still working on this as part of a set of updates to all the Machine Learning on GCP labs.

**Comment by seanlubbers1** [comment]
@joemansfield do you have an expected release date for the updates you're making?

**Comment by joemansfield** [comment]
@seanlubbers1 We're just finishing up testing a workaround for this. We will have this resolved by 19 December.

**Pull request closed without merging**
